//! Word-level compression: common words become a 4-code dictionary hit (1
//! flag + 3 code letters) instead of one code per character -- the same
//! trick 19th/20th-century commercial telegraph codebooks (e.g. Bentley's
//! Complete Phrase Code) used to cut cable costs.
//!
//! The word list and codes (`data/dict_en.json`, compiled into two
//! perfect-hash maps by `build.rs`) were generated by the original
//! project's `tools/build_dictionary.py`, ranked by *expected character
//! savings* (frequency-weighted by word length) using real frequency data
//! from `wordfreq`. A dictionary hit only pays off for words 5+ letters
//! long (4 codes to send the flag+code vs. 5+ codes for the literal word).
//!
//! [`codes::DICT_LOWER`]/[`codes::DICT_TITLE`] cover the two cases worth a
//! cheap flag: the word as stored (lowercase) and sentence-initial
//! capitalization. Any other casing (ALL CAPS, mIxEd case) falls back to
//! plain per-character encoding via [`crate::charset`], as does any word
//! not in the dictionary -- this is a strict optional layer on top of the
//! character-level protocol, never a replacement for it.
//!
//! Word segmentation here assumes space-delimited scripts (English and
//! similar). Languages without spaces between words (Chinese, Japanese,
//! ...) need real word segmentation, not just a different word list -- out
//! of scope for this module.

use crate::charset::{self, Utf8CharDecoder};
use crate::codes;
use crate::framing::{ReadError, Token, TokenReader};

mod data {
    include!(concat!(env!("OUT_DIR"), "/dictionary_data.rs"));
}

/// Byte ranges of maximal `[A-Za-z]+` runs in `text`, in order -- the same
/// segmentation `re.compile(r"[A-Za-z]+")` produces in the original.
fn word_runs(text: &str) -> Vec<(usize, usize)> {
    let mut runs = Vec::new();
    let mut start: Option<usize> = None;
    let mut last_end = 0usize;
    for (i, c) in text.char_indices() {
        if c.is_ascii_alphabetic() {
            if start.is_none() {
                start = Some(i);
            }
            last_end = i + c.len_utf8();
        } else if let Some(s) = start.take() {
            runs.push((s, last_end));
        }
    }
    if let Some(s) = start {
        runs.push((s, last_end));
    }
    runs
}

fn capitalize(lower: &str) -> String {
    let mut chars = lower.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

pub fn encode_text(text: &str) -> Vec<u8> {
    let mut out = Vec::new();
    let mut pos = 0usize;

    for (start, end) in word_runs(text) {
        if start > pos {
            out.extend(charset::encode_text(&text[pos..start]));
        }

        let word = &text[start..end];
        let lower = word.to_lowercase();
        match data::WORD_TO_CODE.get(lower.as_str()) {
            None => out.extend(charset::encode_text(word)),
            Some(code) => {
                if word == lower {
                    out.push(codes::DICT_LOWER);
                    out.extend(code.bytes());
                } else if word == capitalize(&lower) {
                    out.push(codes::DICT_TITLE);
                    out.extend(code.bytes());
                } else {
                    out.extend(charset::encode_text(word)); // ALL CAPS / odd casing: no cheap flag for it
                }
            }
        }

        pos = end;
    }

    if pos < text.len() {
        out.extend(charset::encode_text(&text[pos..]));
    }

    out
}

pub fn decode_codes(code_stream: &[u8]) -> String {
    let mut reader = TokenReader::new(code_stream);
    let mut decoder = Utf8CharDecoder::new();
    let mut result = String::new();

    while reader.has_more() {
        let (kind_is_dict_flag, flag_val) = {
            let saved = reader.pos();
            match reader.read() {
                Ok(Token::Flag(v)) if v == codes::DICT_LOWER || v == codes::DICT_TITLE => (true, v),
                _ => {
                    reader.set_pos(saved);
                    (false, 0)
                }
            }
        };

        if kind_is_dict_flag {
            let mut letters = String::new();
            let mut ok = true;
            for _ in 0..3 {
                if !reader.has_more() {
                    ok = false;
                    break;
                }
                match reader.read() {
                    Ok(Token::Data(v)) => letters.push(v as char),
                    _ => {
                        ok = false;
                        break;
                    }
                }
            }
            if ok {
                if let Some(&word) = data::CODE_TO_WORD.get(letters.as_str()) {
                    if flag_val == codes::DICT_TITLE {
                        result.push_str(&capitalize(word));
                    } else {
                        result.push_str(word);
                    }
                }
                // malformed/unknown code: drop silently and resync at the
                // next token, same recovery philosophy as Utf8CharDecoder.
            }
            continue;
        }

        let token = match reader.read() {
            Ok(t) => t,
            Err(ReadError::EscapeAtEndOfStream) | Err(ReadError::Eof) => break,
        };
        if let Some(ch) = decoder.feed(token) {
            result.push(ch);
        }
    }

    result
}

/// Test/debug accessor mirroring the Python `dictionary._load` used by
/// `test_short_words_dont_get_dictionary_entries`.
#[cfg(test)]
fn all_words() -> impl Iterator<Item = &'static str> {
    data::WORD_TO_CODE.keys().copied()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn roundtrip(text: &str) -> String {
        decode_codes(&encode_text(text))
    }

    #[test]
    fn dictionary_word_roundtrips() {
        assert_eq!(roundtrip("people"), "people");
    }

    #[test]
    fn title_case_roundtrips() {
        assert_eq!(roundtrip("People are here"), "People are here");
    }

    #[test]
    fn all_caps_falls_back_to_literal_not_dictionary() {
        let text = "PEOPLE";
        let encoded = encode_text(text);
        assert!(!encoded.contains(&codes::DICT_LOWER));
        assert!(!encoded.contains(&codes::DICT_TITLE));
        assert_eq!(roundtrip(text), text);
    }

    #[test]
    fn mixed_sentence_roundtrips() {
        let text = "The government should provide information about something important.";
        assert_eq!(roundtrip(text), text);
    }

    #[test]
    fn non_dictionary_word_falls_back_unchanged() {
        let text = "xyzzyqux"; // not a real word, won't be in the dictionary
        assert_eq!(roundtrip(text), text);
    }

    #[test]
    fn punctuation_and_spacing_preserved() {
        let text = "Hello, world! Is this really working? Yes -- because it should.";
        assert_eq!(roundtrip(text), text);
    }

    #[test]
    fn dictionary_hit_is_shorter_than_plain_encoding_for_long_common_words() {
        let text = "government information international";
        let dict_len = encode_text(text).len();
        let plain_len = charset::encode_text(text).len();
        assert!(dict_len < plain_len);
    }

    /// Words <=4 letters can't win (a hit costs 4 codes: flag+3 letters),
    /// so the generator should never have assigned them entries -- verifies
    /// the build_dictionary.py filtering, not just this module's logic.
    #[test]
    fn short_words_dont_get_dictionary_entries() {
        assert!(all_words().all(|w| w.len() >= 5));
    }

    #[test]
    fn empty_and_single_char_no_crash() {
        assert_eq!(roundtrip(""), "");
        assert_eq!(roundtrip("x"), "x");
    }

    #[test]
    fn cjk_text_unaffected_by_dictionary_layer() {
        let text = "你好，世界！";
        assert_eq!(roundtrip(text), text);
    }

    /// Word-boundary edge cases: the `[A-Za-z]+` word-run scanner splits on
    /// any non-ASCII-letter, so apostrophes/hyphens/digits break a run into
    /// separate words (e.g. "don't" -> "don" + "t"), none of which need to
    /// be dictionary entries themselves for the round trip to stay exact --
    /// the charset layer underneath is a strict, always-available fallback
    /// for every character regardless of word segmentation.
    #[test]
    fn contractions_hyphens_and_digits_roundtrip_exactly() {
        for text in [
            "don't stop",
            "well-known information",
            "COVID-19 information about something",
            "it's a test",
            "government123 should",
            "'quoted' government",
        ] {
            assert_eq!(roundtrip(text), text, "failed for {text:?}");
        }
    }
}
